### PR TITLE
first-program

### PR DESCRIPTION
**Pull request by charlie87-hash**

### CODE REVIEW

**Comment by charlie87-hash** [comment]
Corrected the first branch and purged out the other files

**Review by defrank — DISMISSED** [review]
LGTM!

**Comment by charlie87-hash** [comment]
# Requirements


    Requirements include; terminal, py file and correct set up
    The expectations of this exercise is to run print statements using the terminal 
# Summary


    
    Approach taken;
    - Type out the print statements to be printed and name the file ex1.py
    - Open the terminal and navigate to the path where the file is stored locally on the computer
    - run the file by typing: python ex1.py
    - You should see an output of the script displayed in the terminal

## Study drills done    
1. Make your script print another line.

[//]: # (printing things)
[//]: # (print&#40;"Hello World!"&#41;)
[//]: # (print&#40;"Hello Again"&#41;)
[//]: # (print&#40;"I like typing this."&#41;)
[//]: # (print&#40;"This is fun."&#41;)
[//]: # (print&#40;'Yay! Printing.'&#41;)
[//]: # (print&#40;"I'd much rather you 'not'."&#41;)
[//]: # (print&#40;'I "said" do not touch this.'&#41;)
print("I love programming")

3. Make your script print only one of the lines.

[//]: # (    Just comment in all the lines except one line)

4. Put a # (octothorpe) character at the beginning of a line. What did it do? Try to find out what
this character does.

[//]: # (   The octothorpe makes the code block not usable.&#40;It doesn't run&#41;)

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes

[//]: # (    Ran the compiler)

**Test Configuration**:

[//]: # (n/a)
    
# Checklist:
- [ ] My code follows the style guidelines of this exercise
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass locally with my changes

**Review by coverdriver27 — APPROVED** [review]
Lgtm!11

**Pull request merged**
